### PR TITLE
Fix package issue

### PR DESCRIPTION
**Pull request by syohex**
- Fix compilation error with newer Perl(#1)
- Remove needless files
- Fix POD issue
- Improve packaging
- Specify minimum Perl version
- Add travis configuration

Could you give me commit bit and COMAINT of this package on CPAN ? And could you enable travis configuration of this repository ?

### CODE REVIEW

**Comment by lestrrat** [comment]
push one more time and you get travis now :)

**Comment by lestrrat** [comment]
SYOHEX has been added on PAUSE

**Comment by syohex** [comment]
Thanks. However I don't have commit bit of this repository. I can't merge :-(

**Comment by lestrrat** [comment]
Well, I thought maybe you had another small commit to push to trigger travis-ci, but what the heck. I'll merge and add you as collab

**Comment by syohex** [comment]
Thanks

**Pull request merged**
